# Generated by Django 6.0.2 on 2026-02-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
